### ISSUE TITLE
Office 64 bit reportedly not detected

### ISSUE THREAD

**Issue by blazzer** [quandl/quandl-excel-windows#29]
There's a bug report from client which can be interpreted that 64bit office was detected as 32bit by the setup routine, so Excel attempted to load 32bit xll. No further information is available at this point and screenshare has not been attempted.

**Comment by A-Scott-Rowe** [comment]
Issue fixed by [v3.91.0](https://github.com/quandl/quandl-excel-windows/releases/tag/v3.91.0)
